#
# Конифигурация для сайта.
# Скопируйте в файл config.yml и настройте все переменные.
#

### Укажите true, если хотите выполнять приложение в режиме дебага.
debug : false 

### Перечисленные здесь пользователи будут иметь доступ к админке.
security:
    <username> :
        password : <digest>
        role     : ['ROLE_ADMIN']
    
### База данных.
db :
    host     : <host>
    dbname   : <dbname>
    user     : <user>
    password : <password>

### Настройки модели.
model :
    logger_enable : false
