###
### Конифигурация для сайта
###

### Перечисленные здесь пользователи будут иметь доступ к админке.
admin:
    # username : password_hash
    
### База данных пока не используется.
# db: 

### Укажите true, если хотите выполнять приложение в режиме дебага.
debug : false 
