#
# Конифигурация для сайта.
# Скопируйте в файл config.yml и настройте все переменные.
#

### Укажите true, если хотите выполнять приложение в режиме дебага.
debug : false 

### Перечисленные здесь пользователи будут иметь доступ к админке.
security:
    # username : digest
    
### База данных.
# db :
#     host     : 
#     dbname   : 
#     user     : 
#     password : 
