CREATE TABLE `mondai` (
  `mondai_id` int(11) unsigned NOT NULL,
  `title` varchar(255) NOT NULL,
  `is_hidden` tinyint(1) unsigned NOT NULL default '1',
  `content` text NOT NULL,
  `kyoku` enum('ton-1','ton-2','ton-3','ton-4','nan-1','nan-2','nan-3','nan-4') NOT NULL,
  `jikaze` enum('ton','nan','sha','pei') NOT NULL,
  `junme` tinyint(2) NOT NULL,
  `dora` varchar(2) NOT NULL,
  `mochiten` varchar(20) NOT NULL,
  `tehai` varchar(50) NOT NULL,
  `tsumo` varchar(2) NOT NULL,
  `kiri_a` varchar(2) NOT NULL,
  `kiri_b` varchar(2) NOT NULL,
  `kiri_c` varchar(2) NOT NULL,
  PRIMARY KEY  (`mondai_id`),
  KEY `dora` (`dora`),
  KEY `tsumo` (`tsumo`),
  KEY `kiri_a` (`kiri_a`),
  KEY `kiri_b` (`kiri_b`),
  KEY `kiri_c` (`kiri_c`),
  CONSTRAINT `FK_mondai_dora` FOREIGN KEY (`dora`) REFERENCES `pai` (`display`),
  CONSTRAINT `FK_mondai_tsumo` FOREIGN KEY (`tsumo`) REFERENCES `pai` (`display`),
  CONSTRAINT `FK_mondai_kiri_a` FOREIGN KEY (`kiri_a`) REFERENCES `pai` (`display`),
  CONSTRAINT `FK_mondai_kiri_b` FOREIGN KEY (`kiri_b`) REFERENCES `pai` (`display`),
  CONSTRAINT `FK_mondai_kiri_c` FOREIGN KEY (`kiri_c`) REFERENCES `pai` (`display`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
